packages:
  - packages/*
  - apps/*

catalog:
  better-auth: ^1.3.17
  next: ^15.5.4
  tsup: ^8.5.0
  typescript: ^5.9.2
  cmdk: ^1.1.1

catalogs:
  react19:
    '@types/react': ^19.1.13
    react: ^19.1.1
